import type { Metadata } from "next";
import { Geist, Geist_Mono , Instrument_Sans , Inter_Tight} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/ThemeProvider";
import AosAnimate from "@/components/AOS_animate.tsx";
import SlowScroll from "@/components/SlowScroll.tsx";
import Cursor from "@/components/cursor.tsx";

const instrumentSans = Instrument_Sans({
    variable: "--font-instrument-sans",
    subsets: ["latin"],

});

const interTight = Inter_Tight({
    variable: "--font-inter-tight",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru"  suppressHydrationWarning>
        <body className={`${instrumentSans.variable} ${interTight.variable} antialiased scroll-smooth`} suppressHydrationWarning>
        <ThemeProvider>
            <SlowScroll/>
            <Cursor/>
            {children}
            <AosAnimate/>
        </ThemeProvider>
        </body>
        </html>
    );
}