import type {Metadata} from "next";
import {Instrument_Sans, Inter_Tight} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "../components/ThemeProvider";
import AosAnimate from "@/components/AOS_animate";
import SlowScroll from "@/components/SlowScroll";
import Cursor from "@/components/cursor";


const instrumentSans = Instrument_Sans({
    variable: "--font-instrument-sans",
    subsets: ["latin"],
});

const interTight = Inter_Tight({
    variable: "--font-inter-tight",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html suppressHydrationWarning>
        <body
            className={`${instrumentSans.variable} ${interTight.variable} antialiased`}
            suppressHydrationWarning
        >
        <ThemeProvider>
            <SlowScroll>
                <Cursor/>
                {children}
                <AosAnimate/>
            </SlowScroll>
        </ThemeProvider>
        </body>
        </html>
    );
}